### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by offbyone** [WorldconVotingSystems/nomnom#14]
The system needs to be able to generate a report for WSFS. The report should be sent to them on a schedule. 

The report format should meet the specification; currently that's a CSV file with the following structure.

```csv
nominating_ip,nominations.created_at,email_address,reservations.membership_number,categories.name,nominations.field_1,nominations.field_2,nominations.field_3
109.88.203.73,2022-01-15 17:11:46 UTC,foo@example.com,123,A Desolation Called Peace,AMartine,,
109.88.203.73,2022-01-15 19:02:19 UTC,foo@example.com,123,Once & Future 2: Old Engish,Kieron Gillen et al,,
```

```[tasklist]
### Tasks
- [ ] https://github.com/WorldconVotingSystems/nomnom/issues/18
- [ ] https://github.com/WorldconVotingSystems/nomnom/issues/1
- [ ] https://github.com/WorldconVotingSystems/nomnom/issues/20
- [x] https://github.com/WorldconVotingSystems/nomnom/issues/26
```

**Comment by offbyone** [comment]
```csv
id,field_1,field_2,field_3,nominator,category,nomination_date,nomination_ip_address,email,member_number
1,sdfsf,sdfsdfsd,,clyde-staging-1000004,Best Novel,2023-12-24 09:08:19.844568+00:00,100.113.157.9,offline@offby1.net,#1000004
```

This is the report that we write out.

**Comment by offbyone** [comment]
The email plumbing still needs work. otherwise this is done.

**Comment by offbyone** [comment]
This is done.
