### ISSUE TITLE
Refactoring and Evolving

### ISSUE THREAD

**Issue by offbyone** [WorldconVotingSystems/nomnom#153]
This is a roll-up issue for the things I want to do to the code after Glasgow is done, but before we need to collect nominations for Seattle or LA

I want to look into migrating away from environ-config to django-configuration; it looks like it'll fit the needs of the application better, and may make it easier to maintain and extend the configuration

I'd like to try to move from celery to django-q2 as a more django-native background job implementation. Probably with the ORM backend.

I want to get the new developer experience nailed down; starting from a clean checkout, how easy is it to get going?

I want to get the "add a new convention" experience down.

```[tasklist]
### Tasks
- [ ] Investigate migrating to django-configuration
- [ ] Investigate migrating to django-q2
- [ ] Ensure that cloning and running just get-working results in a functional, unthemed instance
- [ ] Ensure that the new convention process is documented and works
```
